name = "CollocationGrids"
uuid = "d95fcbb5-d85b-43ec-af7e-3a9667fb9b7f"
authors = ["Markus-Amano <markus.a.amano@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
TaylorDiff = "b36ab563-344f-407b-a36a-4f200bebf99c"
